version: '3'

services:
    serv_img_crop:
        build: .
        image: serv_img_crop:latest
        container_name: serv_img_crop
        restart: always
        volumes:
            - original:/usr/src/app/uploads/images/original
            - thumbs:/usr/src/app/uploads/images/thumbs
        ports:
            - 127.0.0.1:3000:3000
volumes:
  original:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /uploads/images/original
  thumbs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /uploads/images/thumbs